### PR TITLE
Don't respond to OPTIONS requests - Hoodie core does this now

### PR DESCRIPTION
**Pull request by jameswestnz**
@gr2m: Related to https://github.com/hoodiehq/hoodie/pull/498

### CODE REVIEW

**Comment by jameswestnz** [comment]
This may not be needed... It's more of a clean-up commit in case it causes issues in the future. Need to test this in combination with https://github.com/hoodiehq/hoodie/pull/498 before accepting the PR.

**Comment by gr2m** [comment]
yes LGTM, thanks @jameswestnz! 

Ping @hoodiehq/maintainers @christophwitzko

**Comment by HipsterBrown** [comment]
LGTM! 👍 

Great work @jameswestnz!

**Comment by christophwitzko** [comment]
As `@hoodie/store-server` should also work standalone, I would not remove this.
I don't think it will cause any issues with `hapi-cors-headers`.

**Comment by jameswestnz** [comment]
This is a good point - although I'd suggest that because this line wasn't
allowing the preflight to pass previously (within the latest hoodie
environment, anyway), that it's likely not adding any value?

'Hapi-cors-headers' provides a pretty concise solution to the core
preflight issue in any hapi environment, so feel it's more of a hapi/server
level issue than @hoodie/store-server level. Especially as cors wouldn't be
required if the request is on the same domain.

**Comment by gr2m** [comment]
@christophwitzko I had the same thought, but now agree with @jameswestnz. `hoodie-store-server` is just a hapi plugin, so I would leave it out. We could add an FAQ section on how to add CORS support. We can also put it in the `hoodie-store` demo server here: https://github.com/hoodiehq/hoodie-store/blob/master/example/index.js#L24-L63 and reference it in the FAQ answer — would that work for you?

**Comment by gr2m** [comment]
I’ll merge this in to unblock https://github.com/hoodiehq/hoodie/issues/493, but please keep discussion going. I can follow up with another PR if we come up to another conclusion :)

**Pull request merged**
