### PR TITLE
Assure db folders for leveldb adapter

### PR DESCRIPTION
**Pull request by gr2m**
Workaround for https://github.com/pouchdb/pouchdb/issues/5668
ping @hoodiehq/maintainers

Note: this also needs hoodiehq/hoodie-server#507 to work properly

### CODE REVIEW

**Comment by gr2m** [comment]
rebased on latest master

**Comment by sdvg** [comment]
I tested this on app-tracker but it doesn't seem to work:

When I run the server for the first time (without `.hoodie` directory) and signUp everything seems to work but there's one request that responds with status 500:

```
GET http://127.0.0.1:8080/hoodie/store/api/user%2F9co1mit/_local/_Z0z6AzcwBRkQKVzSMwl0g%3D%3D?

{"error":"OpenError","reason":"IO error: .hoodie/data/user/9co1mit/LOCK: No such file or directory"}
```

The catch function you defined never gets called for me.

tracker account 2016-09-11 21-04-26

**Comment by gr2m** [comment]
okay that is odd, I thought I had it all setup locally, but might have missed something! Can you check it with this PR on `hoodie-server`? https://github.com/hoodiehq/hoodie-server/pull/507

**Comment by gr2m** [comment]
let’s wait with merging this because word is that `express-pouchdb@2` is coming soon

**Comment by gr2m** [comment]
@sdvg good catch! I see the problem, too

**Comment by gr2m** [comment]
ah yes, this will not work without hoodiehq/hoodie-server#507, because only hoodiehq/hoodie-server#507 is using the `server.plugins.store.create` API where I put in the workaround for the `pouchdb-adapter-leveldb` bug. 

I checked it again, and after linking `hoodiehq/hoodie-server#507` (and then you need to link hoodie-server-store into hoodie-server) it all works as expected

**Pull request merged**
